#pragma config(Sensor, S2,     puckS,          sensorEV3_IRSensor)
#pragma config(Sensor, S3,     goalS,          sensorEV3_Color)
#pragma config(Sensor, S4,     wallS,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          jawsM,         tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightM,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          liftM,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	waitForButtonPress();

	while (1){
		int motor_l_enc;
		int motor_r_enc;

		motor_l_enc = getMotorEncoder(leftM);
		motor_r_enc = getMotorEncoder(rightM);

		bFloatDuringInactiveMotorPWM = true;

		displayTextLine(0, "MotorL: %d", motor_l_enc);
		displayTextLine(1, "MotorR: %d", motor_r_enc);

		sleep(2000);
		moveMotorTarget(leftM, 90, 100);
		setMotorReversed(rightM, true);

		moveMotorTarget(rightM, 90, 100);
    sleep(2000);

	}


}
